(let ((default-directory "~/.emacs.d/"))(
normal-top-level-add-subdirs-to-load-path
))

;;install, configure and load el-get if needed
(unless (require 'el-get nil 'noerror)(
	with-current-buffer(
		url-retrieve-synchronously "https://raw.github.com/dimitri/el-get/master/el-get-install.el")(
			let(el-get-master-branch)
			(goto-char(point-max)
		)
		(eval-print-last-sexp)
	)
)
(el-get-elpa-build-local-recipes))
(add-to-list 'el-get-recipe-path "~/.emacs.d/custom/recipes/")

;; Desired packages
(setq el-get-packages '(
	unbound
	color-theme
	powerline
))
(el-get 'sync el-get-packages)

(use-global-map(make-sparse-keymap))
(global-set-key (kbd "SPC") 'self-insert-command)
(global-set-key (kbd "!") 'self-insert-command)
(global-set-key (kbd "\"") 'self-insert-command)
(global-set-key (kbd "$") 'self-insert-command)
(global-set-key (kbd "%") 'self-insert-command)
(global-set-key (kbd "&") 'self-insert-command)
(global-set-key (kbd "'") 'self-insert-command)
(global-set-key (kbd "(") 'self-insert-command)
(global-set-key (kbd ")") 'self-insert-command)
(global-set-key (kbd "*") 'self-insert-command)
(global-set-key (kbd "+") 'self-insert-command)
(global-set-key (kbd "`") 'self-insert-command)
(global-set-key (kbd "-") 'self-insert-command)
(global-set-key (kbd ".") 'self-insert-command)
(global-set-key (kbd "/") 'self-insert-command)
(global-set-key (kbd "0") 'self-insert-command)
(global-set-key (kbd "1") 'self-insert-command)
(global-set-key (kbd "2") 'self-insert-command)
(global-set-key (kbd "3") 'self-insert-command)
(global-set-key (kbd "4") 'self-insert-command)
(global-set-key (kbd "5") 'self-insert-command)
(global-set-key (kbd "6") 'self-insert-command)
(global-set-key (kbd "7") 'self-insert-command)
(global-set-key (kbd "8") 'self-insert-command)
(global-set-key (kbd "9") 'self-insert-command)
(global-set-key (kbd ":") 'self-insert-command)
(global-set-key (kbd ";") 'self-insert-command)
(global-set-key (kbd "<") 'self-insert-command)
(global-set-key (kbd "=") 'self-insert-command)
(global-set-key (kbd ">") 'self-insert-command)
(global-set-key (kbd "?") 'self-insert-command)
(global-set-key (kbd "@") 'self-insert-command)
(global-set-key (kbd "A") 'self-insert-command)
(global-set-key (kbd "B") 'self-insert-command)
(global-set-key (kbd "C") 'self-insert-command)
(global-set-key (kbd "D") 'self-insert-command)
(global-set-key (kbd "E") 'self-insert-command)
(global-set-key (kbd "F") 'self-insert-command)
(global-set-key (kbd "G") 'self-insert-command)
(global-set-key (kbd "H") 'self-insert-command)
(global-set-key (kbd "I") 'self-insert-command)
(global-set-key (kbd "J") 'self-insert-command)
(global-set-key (kbd "K") 'self-insert-command)
(global-set-key (kbd "L") 'self-insert-command)
(global-set-key (kbd "M") 'self-insert-command)
(global-set-key (kbd "N") 'self-insert-command)
(global-set-key (kbd "O") 'self-insert-command)
(global-set-key (kbd "P") 'self-insert-command)
(global-set-key (kbd "Q") 'self-insert-command)
(global-set-key (kbd "R") 'self-insert-command)
(global-set-key (kbd "S") 'self-insert-command)
(global-set-key (kbd "T") 'self-insert-command)
(global-set-key (kbd "U") 'self-insert-command)
(global-set-key (kbd "V") 'self-insert-command)
(global-set-key (kbd "W") 'self-insert-command)
(global-set-key (kbd "X") 'self-insert-command)
(global-set-key (kbd "Y") 'self-insert-command)
(global-set-key (kbd "Z") 'self-insert-command)
(global-set-key (kbd "[") 'self-insert-command)
(global-set-key (kbd "\\") 'self-insert-command)
(global-set-key (kbd "]") 'self-insert-command)
(global-set-key (kbd "^") 'self-insert-command)
(global-set-key (kbd "_") 'self-insert-command)
(global-set-key (kbd "`") 'self-insert-command)
(global-set-key (kbd "a") 'self-insert-command)
(global-set-key (kbd "b") 'self-insert-command)
(global-set-key (kbd "c") 'self-insert-command)
(global-set-key (kbd "d") 'self-insert-command)
(global-set-key (kbd "e") 'self-insert-command)
(global-set-key (kbd "f") 'self-insert-command)
(global-set-key (kbd "g") 'self-insert-command)
(global-set-key (kbd "h") 'self-insert-command)
(global-set-key (kbd "i") 'self-insert-command)
(global-set-key (kbd "j") 'self-insert-command)
(global-set-key (kbd "k") 'self-insert-command)
(global-set-key (kbd "l") 'self-insert-command)
(global-set-key (kbd "m") 'self-insert-command)
(global-set-key (kbd "n") 'self-insert-command)
(global-set-key (kbd "o") 'self-insert-command)
(global-set-key (kbd "p") 'self-insert-command)
(global-set-key (kbd "q") 'self-insert-command)
(global-set-key (kbd "r") 'self-insert-command)
(global-set-key (kbd "s") 'self-insert-command)
(global-set-key (kbd "t") 'self-insert-command)
(global-set-key (kbd "u") 'self-insert-command)
(global-set-key (kbd "v") 'self-insert-command)
(global-set-key (kbd "w") 'self-insert-command)
(global-set-key (kbd "x") 'self-insert-command)
(global-set-key (kbd "y") 'self-insert-command)
(global-set-key (kbd "z") 'self-insert-command)
(global-set-key (kbd "{") 'self-insert-command)
(global-set-key (kbd "|") 'self-insert-command)
(global-set-key (kbd "}") 'self-insert-command)
(global-set-key (kbd "~") 'self-insert-command)

(global-set-key (kbd "DEL") 'backward-delete-char-untabify)

(global-set-key (kbd "M-d") 'forward-char)
(global-set-key (kbd "M-a") 'backward-char)
(global-set-key (kbd "C-d") 'forward-word)
(global-set-key (kbd "C-a") 'backward-word)

(global-set-key (kbd "M-C-d") 'end-of-line)
(global-set-key (kbd "M-C-a") 'move-beginning-of-line)

(global-set-key (kbd "M-S-d") 'next-buffer)
(global-set-key (kbd "M-S-a") 'previous-buffer)
(global-set-key (kbd "C-S-d") 'windmove-right)
(global-set-key (kbd "C-S-a") 'windmove-left)

(global-set-key (kbd "M-w") 'previous-line)
(global-set-key (kbd "M-s") 'next-line)
(global-set-key (kbd "C-w") 'backward-list)
(global-set-key (kbd "C-s") 'forward-list)

(global-set-key (kbd "M-C-w") 'backward-page)
(global-set-key (kbd "M-C-s") 'forward-page)

(global-set-key (kbd "M-S-w") 'beginning-of-buffer)
(global-set-key (kbd "M-S-s") 'end-of-buffer)
(global-set-key (kbd "C-S-w") 'windmove-up)
(global-set-key (kbd "C-S-s") 'windmove-down)

(global-set-key (kbd "M-x") 'execute-extended-command)
(global-set-key (kbd "C-x C-c") 'kill-emacs)
